### ISSUE TITLE
Is it possible to seperate the parent folder?

### ISSUE THREAD

**Issue by Moyf** [chfourie/obsidian-journal-folder#1]
I love this plugin and I think it could change my daily note's template with a more elegant way!

But I have different base folders for different periodic notes,
![image](https://github.com/user-attachments/assets/b95c0960-2154-473a-bc94-027a55f3192a)

And for now it seems that no matter how I set the pattern in Setting, it would always search for `Periodic/Daily`.
![image](https://github.com/user-attachments/assets/839e814f-56e9-4714-8cb2-7088fb3ba464)

So, is it possible for setting different folder?

**Comment by chfourie** [comment]
Good day

Thank you, I am glad you like the plugin.  I believe that you are mixing plugins up in your thinking.  The Journal Folder plugin looks at the folder where the current note resides and uses that as its folder.  You can therefore have multiple journals in multiple folders.  It should be noted however that Journal folder currently **ONLY** consists of the journal header described in its documentation.  As a result also, the Journal Folder configuration does not provide you with any options to configure folders.

Any links that you see outside of the page are provided by **other** plugins.  These plugins are developed and maintained by other developers and may not support multiple folders.  The following plugins come to mind...
- The "Periodic Notes" plugin (a community plugin).  This is the plugin displayed in your first screen shot and is therefore the one causing your confusion.  As mentioned, this is a different plugin which is maintained by a different developer.  This plugin does not support multiple folders.
- The "Calendar" plugin (a community plugin) provides a calendar widget which can be used to navigate notes.  If installed, this plugin's configuration can be found under "Configuration -> Community plugins -> Calendar".  This plugin also does not support multiple folders.
- The "Daily Notes" plugin (a core Obsidian plugin) provides a link in the ribbon for navigating directly to today's note.  The folder where this note resides are configured in the configuration of the daily notes plugin.  This configuration can be found under "Configuration -> Core plugins -> Daily notes".  This plugin only supports a single folder.

Due to the above plugins specifically developer to support a single folder for journal entries, I am planning to create a calendar type widget and ribbon bar button as part of the Journal Folder plugin.  These however are future developments to the plugin.  (i.e. watch this space.). I am hoping to have both of these features developed by the end of the year.

I hope the above helps to clear any confusion and am awaiting your feedback.

**Comment by Moyf** [comment]
Thank you for your detailed reply!
In fact, I am indeed using the PeriodicNote plugin for my daily note management. 

![image](https://github.com/user-attachments/assets/318bb5cf-32ef-4f54-9a2e-fc4a814e60ab)
( When I config like that, it could create file in different note folder)

---

I am very interested in this view of the plugin ↓ because it is more aesthetically pleasing than manually adding links myself.
![image](https://github.com/user-attachments/assets/19cdf582-b7f9-45ab-bf2a-b0f63935d884)
However, I found that the yearly notes and Weekly notes it points to are based on the Daily folder, which is why I asked. 
Perhaps I can refer to your solution and look for a similar view rendering method like dvjs. Thank you again!

**Comment by chfourie** [comment]
Good day.  

The links are supposed to point to the same folder.  It is possible however that there may be an issue as I am using an Obsidian method to sanitise the URL.  If the URL is changed to the shortest possible, and a file with the same name already exists, it could be that the link end up pointing to the existing file in stead of a file in the same folder.  I will check it out and, if that is the case, I will deploy a fix in the next day or two.

As for your screen shot of the configuration that you included in the first post, please take note of the following:
* Those settings determine how the title is formatted and not the file name.
* It does therefore not make sense to include folders in the value as was present in your screen shot.

**Comment by chfourie** [comment]
Good day

My apologies.  After carefully reading through your comments again, I now realise that I completely misunderstood your request.  I now understand that you are attempting to split daily, weekly, monthly and yearly notes into separate folders.  Unfortunately the Journal Folder plugin is specifically written to make use of a single folder for the above.  I am also not planning on adding the option to split them up in the near future.  So if keeping your daily, weekly, monthly and yearly notes in the same folder is a deal breaker for you this plugin will unfortunately not work for you.

Once again my apologies for the misunderstanding.

Charl

**Comment by Moyf** [comment]
> Good day
> 
> My apologies. After carefully reading through your comments again, I now realise that I completely misunderstood your request. I now understand that you are attempting to split daily, weekly, monthly and yearly notes into separate folders. Unfortunately the Journal Folder plugin is specifically written to make use of a single folder for the above. I am also not planning on adding the option to split them up in the near future. So if keeping your daily, weekly, monthly and yearly notes in the same folder is a deal breaker for you this plugin will unfortunately not work for you.
> 
> Once again my apologies for the misunderstanding.
> 
> Charl

Hahaha, it's okay! I also realized after carefully reading the plugin's instructions that it was specifically developed for "date notes in one folder"—equivalent to having multiple similar "diary folders" at different locations in the notes.

While researching the source code, I found that you were reading the `parent` of the current note, so I wondered if changing it to the Root directory and adding "path format configuration" would work... 
However, ultimately, my needs do not align with the plugin's original development intent, so I think I will try to explore other options! 😄

Thank you for your patience and response; it is still a very good plugin!
